// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SC_Backend.DataContext;

#nullable disable

namespace SC_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260827172740_GPIGameKoloneCK")]
    partial class GPIGameKoloneCK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SC_Backend.DataModels.Game", b =>
                {
                    b.Property<int>("GamesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("games_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GamesId"));

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("GameSettingsId")
                        .HasColumnType("integer")
                        .HasColumnName("game_settings_id");

                    b.Property<bool>("IsRanked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ranked");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("status");

                    b.Property<string>("WinningTeam")
                        .HasColumnType("text")
                        .HasColumnName("winning_team");

                    b.HasKey("GamesId")
                        .HasName("games_pkey");

                    b.HasIndex("GameSettingsId");

                    b.ToTable("games", null, t =>
                        {
                            t.HasCheckConstraint("CK_valid_duration_seconds", "duration_seconds IS NULL OR end_time IS NULL OR duration_seconds <= EXTRACT(EPOCH FROM(end_time - start_time))");

                            t.HasCheckConstraint("CK_valid_end_time", "end_time IS NULL OR (end_time > start_time)");
                        });
                });

            modelBuilder.Entity("SC_Backend.DataModels.GamePlayer", b =>
                {
                    b.Property<int>("GamePlayersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("game_players_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GamePlayersId"));

                    b.Property<double>("Accuracy")
                        .HasColumnType("double precision")
                        .HasColumnName("accuracy");

                    b.Property<short?>("EloChange")
                        .HasColumnType("smallint")
                        .HasColumnName("elo_change");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("score");

                    b.Property<string>("TeamColor")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("team_color");

                    b.HasKey("GamePlayersId")
                        .HasName("game_players_pkey");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("game_players", null, t =>
                        {
                            t.HasCheckConstraint("CK_game_players_score", "score >= 0");

                            t.HasCheckConstraint("CK_game_players_team_color", "team_color IN ('Red','Blue')");
                        });
                });

            modelBuilder.Entity("SC_Backend.DataModels.GameSetting", b =>
                {
                    b.Property<int>("GameSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("game_settings_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GameSettingsId"));

                    b.Property<bool>("HasPowerUps")
                        .HasColumnType("boolean")
                        .HasColumnName("has_powerups");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<int>("NumberOfMines")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_mines");

                    b.Property<int?>("StartTimeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("start_time_seconds");

                    b.Property<int>("TeamSize")
                        .HasColumnType("integer")
                        .HasColumnName("team_size");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.Property<string>("WinCondition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("win_condition");

                    b.HasKey("GameSettingsId")
                        .HasName("game_settings_pkey");

                    b.HasIndex("WinCondition", "Width", "Height", "NumberOfMines")
                        .HasDatabaseName("IX_game_settings_template_lookup");

                    b.ToTable("game_settings", null, t =>
                        {
                            t.HasCheckConstraint("CK_game_settings_height", "height >= 9 AND height <= 50");

                            t.HasCheckConstraint("CK_game_settings_mines_fit", "number_of_mines < (width * height)");

                            t.HasCheckConstraint("CK_game_settings_number_of_mines", "number_of_mines >= 10 AND number_of_mines <= 500");

                            t.HasCheckConstraint("CK_game_settings_start_time_seconds", "start_time_seconds IS NULL OR (start_time_seconds >= 30 AND start_time_seconds <= 1200)");

                            t.HasCheckConstraint("CK_game_settings_team_size", "team_size >= 1 AND team_size <= 3");

                            t.HasCheckConstraint("CK_game_settings_width", "width >= 9 AND width <= 50 ");

                            t.HasCheckConstraint("CK_game_settings_win_condition", "win_condition IN ('Race','TimeRush')");
                        });
                });

            modelBuilder.Entity("SC_Backend.DataModels.Move", b =>
                {
                    b.Property<int>("MovesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("moves_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovesId"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<string>("MoveLog")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("move_log");

                    b.HasKey("MovesId")
                        .HasName("moves_pkey");

                    b.HasIndex("GameId");

                    b.ToTable("moves");
                });

            modelBuilder.Entity("SC_Backend.DataModels.User", b =>
                {
                    b.Property<int>("UsersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("users_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsersId"));

                    b.Property<DateOnly>("Datecreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("datecreated")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<short?>("Elo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("elo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("password_hash");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("user_role")
                        .HasDefaultValueSql("'NotSet'::character varying");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("UsersId")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "users_username_key")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("CK_users_elo", "elo >=0 AND elo <=  32767");

                            t.HasCheckConstraint("CK_users_email", "email LIKE '%@%'");

                            t.HasCheckConstraint("CK_users_user_role", "user_role IN ('NotSet','User','Admin')");
                        });
                });

            modelBuilder.Entity("SC_Backend.DataModels.UserStats", b =>
                {
                    b.Property<int>("GameSettingId")
                        .HasColumnType("integer")
                        .HasColumnName("game_setting_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<bool>("IsRanked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ranked");

                    b.Property<int>("GamesPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("games_played");

                    b.Property<int>("Losses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("losses");

                    b.Property<long>("PlayTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("playtime");

                    b.Property<int>("Wins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("wins");

                    b.HasKey("GameSettingId", "UserId", "IsRanked");

                    b.HasIndex("UserId");

                    b.ToTable("user_stats", null, t =>
                        {
                            t.HasCheckConstraint("CK_user_stats_games_played", "games_played >= 0");

                            t.HasCheckConstraint("CK_user_stats_losses", "losses >= 0");

                            t.HasCheckConstraint("CK_user_stats_playtime", "playtime >= 0");

                            t.HasCheckConstraint("CK_user_stats_valid_outcomes", "(wins + losses) <= games_played");

                            t.HasCheckConstraint("CK_user_stats_wins", "wins >= 0");
                        });
                });

            modelBuilder.Entity("SC_Backend.DataModels.Game", b =>
                {
                    b.HasOne("SC_Backend.DataModels.GameSetting", "GameSettings")
                        .WithMany("Game")
                        .HasForeignKey("GameSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSettings");
                });

            modelBuilder.Entity("SC_Backend.DataModels.GamePlayer", b =>
                {
                    b.HasOne("SC_Backend.DataModels.Game", "Game")
                        .WithMany("GamePlayers")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("gamePlayers_gameId_fkey");

                    b.HasOne("SC_Backend.DataModels.User", "Player")
                        .WithMany("GamePlayers")
                        .HasForeignKey("PlayerId")
                        .IsRequired()
                        .HasConstraintName("gamePlayers_playerId_fkey");

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SC_Backend.DataModels.Move", b =>
                {
                    b.HasOne("SC_Backend.DataModels.Game", "Game")
                        .WithMany("Moves")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("moves_gameid_fkey");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SC_Backend.DataModels.UserStats", b =>
                {
                    b.HasOne("SC_Backend.DataModels.GameSetting", "GameSetting")
                        .WithMany()
                        .HasForeignKey("GameSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SC_Backend.DataModels.User", "User")
                        .WithMany("UserStats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSetting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SC_Backend.DataModels.Game", b =>
                {
                    b.Navigation("GamePlayers");

                    b.Navigation("Moves");
                });

            modelBuilder.Entity("SC_Backend.DataModels.GameSetting", b =>
                {
                    b.Navigation("Game");
                });

            modelBuilder.Entity("SC_Backend.DataModels.User", b =>
                {
                    b.Navigation("GamePlayers");

                    b.Navigation("UserStats");
                });
#pragma warning restore 612, 618
        }
    }
}
