// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SC_Backend.DataContext;

#nullable disable

namespace SC_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SC_Backend.DataModels.Game", b =>
                {
                    b.Property<int>("GamesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("games_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GamesId"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_time");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("status");

                    b.HasKey("GamesId")
                        .HasName("games_pkey");

                    b.ToTable("games");
                });

            modelBuilder.Entity("SC_Backend.DataModels.GamePlayer", b =>
                {
                    b.Property<int>("GamePlayersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("game_players_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GamePlayersId"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("score");

                    b.Property<string>("TeamColor")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("team_color");

                    b.HasKey("GamePlayersId")
                        .HasName("game_players_pkey");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("game_players");
                });

            modelBuilder.Entity("SC_Backend.DataModels.GameSetting", b =>
                {
                    b.Property<int>("GameSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("game_settings_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GameSettingsId"));

                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<int>("NumberOfMines")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_mines");

                    b.Property<int>("StartTimeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("start_time_seconds");

                    b.Property<string>("TimeFormat")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("time_format");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("GameSettingsId")
                        .HasName("game_settings_pkey");

                    b.HasIndex("GameId");

                    b.ToTable("game_settings");
                });

            modelBuilder.Entity("SC_Backend.DataModels.Move", b =>
                {
                    b.Property<int>("MovesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("moves_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovesId"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<string>("MoveLog")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("move_log");

                    b.HasKey("MovesId")
                        .HasName("moves_pkey");

                    b.HasIndex("GameId");

                    b.ToTable("moves");
                });

            modelBuilder.Entity("SC_Backend.DataModels.User", b =>
                {
                    b.Property<int>("UsersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("users_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsersId"));

                    b.Property<DateOnly>("Datecreated")
                        .HasColumnType("date")
                        .HasColumnName("datecreated");

                    b.Property<short?>("Elo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("elo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("email");

                    b.Property<string>("UserRole")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("user_role")
                        .HasDefaultValueSql("'User'::character varying");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("UsersId")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "users_username_key")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("SC_Backend.DataModels.GamePlayer", b =>
                {
                    b.HasOne("SC_Backend.DataModels.Game", "Game")
                        .WithMany("GamePlayers")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("gamePlayers_gameId_fkey");

                    b.HasOne("SC_Backend.DataModels.User", "Player")
                        .WithMany("GamePlayers")
                        .HasForeignKey("PlayerId")
                        .IsRequired()
                        .HasConstraintName("gamePlayers_playerId_fkey");

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SC_Backend.DataModels.GameSetting", b =>
                {
                    b.HasOne("SC_Backend.DataModels.Game", "Game")
                        .WithMany("GameSettings")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("gameSettings_gameId_fkey");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SC_Backend.DataModels.Move", b =>
                {
                    b.HasOne("SC_Backend.DataModels.Game", "Game")
                        .WithMany("Moves")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("moves_gameid_fkey");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SC_Backend.DataModels.Game", b =>
                {
                    b.Navigation("GamePlayers");

                    b.Navigation("GameSettings");

                    b.Navigation("Moves");
                });

            modelBuilder.Entity("SC_Backend.DataModels.User", b =>
                {
                    b.Navigation("GamePlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
